name: iChat
main: LDX\iChat\Main
version: "1.0"
api: [1.6.0]
load: POSTWORLD
author: LDX
website: https://github.com/LDX-MCPE/iChat
commands:
  chat:
    description: "Allows players to toggle chat."
    usage: "/chat <on/off>"
    permission: ichat.command.chat
  mute:
    description: "Mutes a player, preventing them from chatting."
    usage: "/mute <player>"
    permission: ichat.command.mute
  unmute:
    description: "Unmutes a player, allowing them to chat again."
    usage: "/unmute <player>"
    permission: ichat.command.unmute
permissions:
  ichat:
    description: "Allows access to all iChat features."
    default: false
    children:
      ichat.*:
        description: "Allows access to all iChat features."
        default: false
      ichat.command:
        description: "Allows access to all iChat commands."
        default: false
        children:
          ichat.command.*:
            description: "Allows access to all iChat commands."
            default: false
          ichat.command.chat:
            description: "Allows access to the chat command."
            default: true
          ichat.command.mute:
            description: "Allows access to the mute command."
            default: op
          ichat.command.unmute:
            description: "Allows access to the unmute command."
            default: op
      ichat.bypass:
        description: "Allows you to bypass chat filters."
        default: op
